-- UPLOAD 테이블 생성

CREATE TABLE UPLOAD(
	UPLOAD_NO NUMBER(5) PRIMARY KEY,		-- 번호
	UPLOAD_WRITER VARCHAR2(30) NOT NULL,	-- 작성자
	UPLOAD_TITLE VARCHAR2(200) NOT NULL,	-- 제목
	UPLOAD_CONTENT VARCHAR2(1500) NOT NULL, -- 내용
	UPLOAD_PWD VARCHAR2(30) NOT NULL,		-- 비밀번호
	UPLOAD_FILE VARCHAR2(500),				-- 파일명
	UPLOAD_HIT NUMBER(5) DEFAULT 0,			-- 조회수
	UPLOAD_DATE DATE,						-- 작성일
	UPLOAD_UPDATE DATE						-- 수정일
);