-- shop_cart 테이블 생성

CREATE TABLE SHOP_CART(
	CART_NUM NUMBER(5) PRIMARY KEY,		-- 카트 번호
	CART_PNUM NUMBER(5) NOT NULL,		-- 상품 제품 번호
	CART_USERID VARCHAR2(30) NOT NULL,	-- 카트 사용자 아이디
	CART_PNAME VARCHAR2(100) NOT NULL,	-- 상품 이름
	CART_PQTY NUMBER(5) NOT NULL,		-- 상품 수량
	CART_PRICE NUMBER(8) NOT NULL,		-- 상품 가격
	CART_PSPEC VARCHAR2(20) NOT NULL,	-- 상품 스펙
	CART_PIMAGE VARCHAR2(500)			-- 상품 이미지
);

