-- shop_category 테이블 생성
CREATE TABLE SHOP_CATEGORY(
	CATEGORY_NUM NUMBER(3) PRIMARY KEY,		-- 카테고리 번호
	CATEGORY_CODE VARCHAR2(8) NOT NULL,		-- 카테고리 코드
	CATEGORY_NAME VARCHAR2(100) NOT NULL	-- 카테고리 이름
);